#!/bin/bash

user_dir=`pwd`
bin_dir=`dirname $user_dir/$0`

host="localhost"
port="8090"

cd $bin_dir
if [ $# -ne 1 ];then
echo -e "[Usage]: $0 [wf_name]\n删除工作流"
exit 1
fi
wfname=$1
result=`curl -s -XGET "http://$host:$port/akkaflow/workflow/$wfname?action=del"`

echo $result
