#!/bin/bash

cd `dirname $0`
source ./head.sh

if [ $# -lt 1 ];then
printf "【使用】\n\takka workflow -run [--param xxx=xx&xx=xx] <wf_name>\n"
printf "【说明】\n\t通过参数让工作流生成实例\n"
printf "【示例】\n\takka workflow -run --param stadate=2017-12-12&city=guangzhou wf_parall_sum\n"
exit 1
fi

param=""
while [ $# -gt 0 ];do
    case "$1" in
      --param)
        shift
        param=$1
        shift;;
      *)
       wf_name=$1
       shift
       ;;
    esac
done

if [ $wf_name == "" ];then
    echo "请输入工作流名称"
    exit 1
fi

result=`curl -s -XGET "http://$host:$port/akkaflow/workflow/$wf_name?action=run&$param"`
echo $result | iconv -f utf8 -t $local_lang
echo ""
