#!/bin/bash
cd `dirname $0`
source ./head.sh

function get_hf
{
    local len=$1
    local str=""
    ((len=len-1))
    for i in `seq 0 $len`;do
       if [ $i -ne 0 ] ; then
         str=$str"####"
       fi
    done
    str=$str"+--- "
    printf "${YELLOW}$str${NC}\n"
}

function f_node
{
    local id=$1
    local level=$2
    ((level=level+1))
    akka_mysql -s -N -e "use $mysql_db;
select id,is_leaf,a.name,creator,coor_enable,description
from (
  select id,is_leaf,name from directory where pid = '$id'
) a left outer join (
  select name,creator,coor_enable,if(length(description) > 60,concat(substring(description,1,60),'...'),description) description
  from workflow
) b on a.name = b.name
    " 2>/dev/null | while read line;do
        local cid=`echo $line |cut -d ' ' -f 1`
        local name=`echo $line |cut -d ' ' -f 3`
        local is_leaf=`echo $line |cut -d ' ' -f 2`
        local creator=`echo $line |cut -d ' ' -f 4`
        local coor_enable=`echo $line |cut -d ' ' -f 5`
        local description=`echo $line |cut -d ' ' -f 6-`
        if [ $is_leaf -eq 0 ];then
            name=${BLUE}$name${NC}
        elif [ $coor_enable -eq 1 ];then
            name="${GREEN}$name${NC}   [$creator]  [$description]"
        else
            name="${RED}$name${NC}   [$creator]  [$description]"
        fi
        tmp=`get_hf $level`
        printf "${tmp//#/ }$name\n"
        f_node $cid $level
    done
}
printf "=================================${GREEN}工作流列表${NC}=====================================\n"

pid_arr=(-1)
if [ $# -eq 1 ];then
    pname=$1
    pid_arr=(`akka_mysql -s -N -e "use $mysql_db;select id from directory where name = '$pname'" 2>/dev/null`)
fi
for pid in ${pid_arr[*]}
do
    f_node $pid 0
done
#f_node $pid 0

echo ""