#!/bin/bash

cd `dirname $0`
source ./head.sh

if [ $# -lt 1 ];then
    printf "【使用】\n\takka workflow -trigger <工作流名称> [--blood]\n"
    printf "【说明】\n\t触发运行指定工作流，若指定--blood，则会依次触发后续与之有血缘关系的工作流\n"
    printf "【示例】\n\takka workflow -trigger wf_parall_sum\n"
    exit 1
fi

blood_type=0
while [ $# -gt 0 ];do
    case "$1" in
      --blood)
        blood_type=1
        shift;;
      *)
       wf_name=$1
       shift;;
    esac
done

if [ $blood_type -eq 0 ]; then
    result=`curl -s -XGET "http://$host:$port/akkaflow/workflow/$wf_name?action=trigger"`
else
    result=`curl -s -XGET "http://$host:$port/akkaflow/workflow/$wf_name?action=trigger-blood"`
fi
echo $result | iconv -f utf8 -t $local_lang
#echo "echo $result | iconv -f utf8 -t $local_lang"
#echo $result
echo ""
