#!/bin/bash
user_dir=`pwd`
cd `dirname $0`
source ./head.sh

if [ $# -ne 1 ];then
printf "【使用】\n\takka workflow -check <xml文件>\n"
printf "【说明】\n\t测试某一工作流定义xml文件是否合法\n"
printf "【示例】\n\takka workflow -check ~/akkaflow/xmlconfig/workflow/example/wf_parall_sum.xml\n"
exit 1
fi

file=$1
is_asoluted=`echo $file | grep -E "^\s*\/" | wc -l`
if [ $is_asoluted -eq 0 ];then
    file=$user_dir/$file
fi
con=`iconv -f ${local_lang} -t utf8 $file |sh ./url-encode|awk '{str=str"%0a"$0} END{print str}'`
result=`curl -s -XPOST -d "xml=$con" "http://$host:$port/akkaflow/workflow?action=check"`

echo $result | iconv -f utf8 -t $local_lang
echo ""
