#!/bin/bash
cd `dirname $0`
source ./head.sh

##显示基本信息
function f_base()
{
    coor_name=$1
    coor_data=`
    local_mysql -s -N -e "use wf;
    select name c1,creator c2,param c3,dir c4,cron c5,depends c6,
           triggers c7,concat(stime,'~',etime) c8,if(is_enabled = 1,'可用','不可用') c9,description c10,create_time c11
    from coordinator where name='$coor_name'
    " 2>/dev/null
    `


    echo -e "=================================${GREEN}调度器信息${NC}====================================="
    echo "$coor_data" | awk -F '\t' '{
        print "调 度 器: "$1
        print "状    态: "$9
        print "目    录: "$4
        print "创 建 者: "$2
        print "创建时间: "$11
        print "生效时间: "$8
        print "参   数: "$3
        print "时间触发: "$5
        print "前置依赖: "$6
        print "后置触发: "$7
        print "描    述: "$10
    }'
}

##显示日志
function f_log()
{
    coor_name=$1
    echo -e "=================================${GREEN}调度器日志信息${NC}====================================="
    local_mysql -e "use wf;
    select title 日志信息, content 内容 from (
      select concat('[',level,'] [',stime,']') title,content,stime
      from log_record where name = '$coor_name' and ctype='COORDINATOR'
      order by stime desc limit 20
    ) aa order by stime
    "  2>/dev/null
}

##显示xml
function f_xml()
{
    coor_name=$1
    echo -e "=================================${GREEN}调度器xml信息${NC}====================================="
    local_mysql -s -e "use wf;
    select xml_str from coordinator where name='$coor_name'
    "  2>/dev/null | awk '{gsub(/\\\\n/,"@@@@",$0);print $0}' | awk '{gsub(/\\n/,"\n",$0);print $0}' |  awk '{gsub(/@@@@/,"\\\\n",$0);print $0}'
    echo ""
}


if [ $# -lt 1 ];then
echo -e "【使用】\n\takka coor -info [-xml] <coor_name>"
echo -e "【说明】\n\t显示调度器相关信息,若加-xml，则显示调度器xml信息,若加-log，则显示调度器日志."
echo -e "【示例】\n\takka coor -info coor_parall_sum"
echo -e "\takka coor -info -log coor_parall_sum"
echo -e "\takka coor -info -xml coor_parall_sum\n"
exit 1
fi

show_type="base"
while [ $# -gt 0 ];do
    case "$1" in
      --xml)
        show_type="xml"
        shift;;
      --log)
        show_type="log"
        shift;;
      *)
       coor_name=$1
       shift
       ;;
    esac
done

if [ "$show_type" == "xml" ];then
    f_xml $coor_name
elif [ "$show_type" == "log" ];then
    f_log $coor_name
else
    f_base $coor_name 
    f_log $coor_name
fi
