#!/bin/bash

cd `dirname $0`
source ./head.sh

if [ $# -ne 1 ];then
echo -e "【使用】\n\takka instance -del [instance_id]"
echo -e "【说明】\n\t删除指定运行中的工作流实例"
echo -e "【示例】\n\takka instance -del 96e66660\n"
exit 1
fi
instance_id=$1
result=`curl -s -XGET "http://$host:$port/akkaflow/workflow/instance/$instance_id?action=del"`
echo $result | iconv -f utf8 -t $local_lang
echo ""
