#!/bin/bash
cd `dirname $0`
source ./head.sh

if [ $# -lt 1 ];then
echo -e "【使用】\n\takka instance -search [--sdate yyyy-mm-dd] [--edate yyyy-mm-dd] [--creator xxx] [--status 成功|失败|杀死|运行] [--key xxxx]"
echo -e "【说明】\n\t根据条件去查找工作流实例"
echo -e "【示例】\n\takka instance -search --status 失败"
echo -e "\takka instance -search --sdate 2018-01-10 --edate 2018-01-11 --creator Unknown --status 失败 --key wf_\n"
exit 1
fi

stadate=`date +'%F'`
sdate="$stadate"
edate="$stadate"
creator="-1"
status="-1"
keyword=""

while [ $# -gt 0 ];do
    case "$1" in
      --sdate)
        shift
        sdate="$1"
        shift;;
      --edate)
        shift
        edate="$1"
        shift;;
      --creator)
        shift
        creator="$1"
        shift;;
      --status)
        shift
        status="$1"
        if [ "$status" == "成功" ];then
            status=3
        elif [ "$status" == "失败" ];then
            status=4
        elif [ "$status" == "杀死" ];then
            status=5
        elif [ "$status" == "运行" ]; then
            status=1
        else
            echo "ERROR!状态错误!"
            exit 1
        fi
        shift;;
      --key)
        shift
        keyword="$1"
        shift;;
      *)
        shift;;
    esac
done

echo "=================================查询结果====================================="
akka_mysql -e "use $mysql_db;
select id 实例ID,name 工作流,
       case when status = '0' then '就绪'
           when status = '1' then '运行中'
           when status = '2' then '挂起'
           when status = '3' then '成功'
           when status = '4' then '失败'
           when status = '5' then '杀死'
           else '--' end 状态,
       stime 开始时间,
       etime 结束时间,UNIX_TIMESTAMP(if(etime is null,curtime(),etime)) - UNIX_TIMESTAMP(STIME) 运行时长
from workflow_instance
where date_format(stime,'%Y-%m-%d') between '${sdate}' and '${edate}'
  and (id like '%${keyword}%' or name like '%${keyword}%')
  and (status = '${status}' or '${status}' = '-1')
  and (creator = '${creator}' or '${creator}' = '-1')
order by stime desc limit 500
" 2>/dev/null

len=`akka_mysql -s -N -e "use $mysql_db;
select count(1)
from workflow_instance
where date_format(stime,'%Y-%m-%d') between '${sdate}' and '${edate}'
  and (id like '%${keyword}%' or name like '%${keyword}%')
  and (status = '${status}' or '${status}' = '-1')
  and (creator = '${creator}' or '${creator}' = '-1')
order by stime desc limit 500
" 2>/dev/null`

echo -e "共$len条记录(最多显示500条记录)\n"