#!/bin/bash

user_dir=`pwd`
cd `dirname $0`
source ./head.sh

if [ $# -ne 1 ];then
echo -e "【使用】\n\takka workflow -add <xml文件>"
echo -e "【说明】\n\t添加某一工作流xml文件"
echo -e "【示例】\n\takka workflow -add ~/akkaflow/xmlconfig/workflow/example/wf_parall_sum.xml\n"
exit 1
fi

file=$1
is_asoluted=`echo $file | grep -E "^\s*\/" | wc -l`
if [ $is_asoluted -eq 0 ];then
    file=$user_dir/$file
fi
dir=`get_fullpath "$file"`
filename=`basename $1`
file=$dir"/"$filename
xml_str=`iconv -f ${local_lang} -t utf8 $file |sh ./url-encode|awk '{str=str"%0a"$0} END{print str}'`
file_str=`echo $file | iconv -f ${local_lang} -t utf8 | sh ./url-encode`
result=`curl -s -XPOST -d "xml=$xml_str" "http://$host:$port/akkaflow/workflow?action=add&path=$file_str"`

echo $result | iconv -f utf8 -t $local_lang
echo ""