#!/bin/bash

cd `dirname $0`
source ./head.sh

if [ $# -ne 1 ];then
echo -e "【使用】\n\takka workflow -del <工作流名称>"
echo -e "【说明】\n\t删除指定工作流"
echo -e "【示例】\n\takka workflow -del wf_parall_sum\n"
exit 1
fi
wf_name=$1
result=`curl -s -XGET "http://$host:$port/akkaflow/workflow/$wf_name?action=del"`
echo $result | iconv -f utf8 -t $local_lang
echo ""
