#!/bin/bash

cd `dirname $0`
source ./head.sh

if [ $# -ne 1 ];then
printf "【使用】\n\takka instance -rerun [instance_id]\n"
printf "【说明】\n\t重跑指定运行中的工作流实例\n"
printf "【示例】\n\takka instance -rerun 96e66660\n"
exit 1
fi
instance_id=$1
result=`curl -s -XGET "http://$host:$port/akkaflow/workflow/instance/$instance_id?action=rerun"`
echo $result | iconv -f utf8 -t $local_lang
echo ""
