#!/bin/bash

cd `dirname $0`
source ./head.sh

if [ $# -ne 1 ];then
printf "【使用】\n\takka workflow -trigger <工作流名称>\n"
printf "【说明】\n\t触发运行指定工作流\n"
printf "【示例】\n\takka workflow -trigger wf_parall_sum\n"
exit 1
fi
wf_name=$1
result=`curl -s -XGET "http://$host:$port/akkaflow/workflow/$wf_name?action=trigger"`
echo $result | iconv -f utf8 -t $local_lang
echo ""
