#!/bin/bash

user_dir=`pwd`
script_dir=`dirname "$0"`

cd $script_dir/..
mkdir -p logs
printf "开始启动Master热备份节点...\n"
printf "启动日志请查看[根目录]/logs/run.log\n"
nohup bin/master-standby 1>> logs/run.log 2>1 &