#!/bin/bash

user_dir=`pwd`
bin_dir=`dirname $user_dir/$0`
cd $bin_dir
source ./head.sh

if [ $# -ne 1 ];then
echo -e "[Usage]: $0 [instance_id]\nָ"
exit 1
fi
instance_id=$1
result=`curl -s -XGET "http://$host:$port/akkaflow/workflow/instance/$instance_id?action=rerun"`

echo $result
cd $user_dir
