#!/bin/bash

user_dir=`pwd`
bin_dir=`dirname $0`
cd $bin_dir
source ./head.sh

result=`curl -s -XGET "http://$host:$port/akkaflow/cluster?action=shutdown"`
echo $result | iconv -f utf8 -t $local_lang
