#!/bin/bash

user_dir=`pwd`
bin_dir=`dirname $user_dir/$0`
cd $bin_dir
source ./head.sh
if [ $# -ne 1 ];then
echo -e "[Usage]: $0 [wf_file]\n添加或替换工作流"
exit 1
fi
file=$1
con=`cat $file |./url-encode|awk '{str=str"%0a"$0} END{print str}'`
result=`curl -s -XPOST -d "content=$con" "http://$host:$port/akkaflow/workflow?action=add"`

echo $result
cd $user_dir
