#!/bin/bash

user_dir=`pwd`
bin_dir=`dirname $user_dir/$0`

host="localhost"
port="8090"
cd $bin_dir
if [ $# -ne 1 ];then
echo -e "[Usage]: $0 [coorfile]\n添加或替换coor"
exit 1
fi
file=$1
con=`cat $file |./url-encode|awk '{str=str$0} END{print str}'`
result=`curl -s  -XPOST -d "content=$con" "http://$host:$port/akkaflow/coor?action=add"`

echo $result
cd $user_dir
